//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CloneHistory
    {
        public int CloneID { get; set; }
        public string OrderNum { get; set; }
        public int ID { get; set; }
        public string Sn { get; set; }
        public string StorageNum { get; set; }
        public string StorageName { get; set; }
        public string LocalNum { get; set; }
        public string LocalName { get; set; }
        public Nullable<int> LocalType { get; set; }
        public string ProductNum { get; set; }
        public string BarCode { get; set; }
        public string ProductName { get; set; }
        public string BatchNum { get; set; }
        public double Num { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string CreateUser { get; set; }
        public string CreateName { get; set; }
        public string Remark { get; set; }
    }
}
