//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StorageEntities : DbContext
    {
        public StorageEntities()
            : base("name=StorageEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bad> Bad { get; set; }
        public virtual DbSet<BadType> BadType { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Delivery> Delivery { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Jurisdiction> Jurisdiction { get; set; }
        public virtual DbSet<Metering> Metering { get; set; }
        public virtual DbSet<MoveBank> MoveBank { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductCategory> ProductCategory { get; set; }
        public virtual DbSet<Relation> Relation { get; set; }
        public virtual DbSet<ReturnPrduct> ReturnPrduct { get; set; }
        public virtual DbSet<ReturnPrductType> ReturnPrductType { get; set; }
        public virtual DbSet<Storehouse> Storehouse { get; set; }
        public virtual DbSet<Supplier> Supplier { get; set; }
        public virtual DbSet<SupplierType> SupplierType { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<WareHouse> WareHouse { get; set; }
        public virtual DbSet<WareHouseType> WareHouseType { get; set; }
        public virtual DbSet<Warehousing> Warehousing { get; set; }
        public virtual DbSet<WareProduct> WareProduct { get; set; }
        public virtual DbSet<WareState> WareState { get; set; }
        public virtual DbSet<WareStateType> WareStateType { get; set; }
        public virtual DbSet<WhState> WhState { get; set; }
        public virtual DbSet<WhereDepot> WhereDepot { get; set; }
    }
}
