//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportParams
    {
        public int ID { get; set; }
        public string ParamNum { get; set; }
        public string ReportNum { get; set; }
        public string InputNo { get; set; }
        public string ParamName { get; set; }
        public string ShowName { get; set; }
        public string ParamType { get; set; }
        public string ParamData { get; set; }
        public string DefaultValue { get; set; }
        public string ParamElement { get; set; }
        public string Remark { get; set; }
    }
}
