//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnPrduct
    {
        public int RPid { get; set; }
        public Nullable<int> Sid { get; set; }
        public Nullable<int> RPnum { get; set; }
        public Nullable<int> RTid { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public Nullable<int> Wid { get; set; }
    
        public virtual ReturnPrductType ReturnPrductType { get; set; }
        public virtual User User { get; set; }
        public virtual Warehousing Warehousing { get; set; }
        public virtual WareState WareState { get; set; }
    }
}
