//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplier()
        {
            this.Warehousing = new HashSet<Warehousing>();
        }
    
        public int SlId { get; set; }
        public Nullable<int> SlTypeId { get; set; }
        public string SlrName { get; set; }
        public string SlDescribe { get; set; }
        public string SlContacts { get; set; }
        public string SlIphone { get; set; }
        public string SlAddress { get; set; }
    
        public virtual SupplierType SupplierType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Warehousing> Warehousing { get; set; }
    }
}
