//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysResource
    {
        public int ID { get; set; }
        public string ResNum { get; set; }
        public string ResName { get; set; }
        public string ParentNum { get; set; }
        public int Depth { get; set; }
        public string ParentPath { get; set; }
        public int ChildCount { get; set; }
        public int Sort { get; set; }
        public short IsHide { get; set; }
        public short IsDelete { get; set; }
        public string Url { get; set; }
        public string CssName { get; set; }
        public System.DateTime CreateTime { get; set; }
        public short Depart { get; set; }
        public short ResType { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public string CreateUser { get; set; }
        public string UpdateUser { get; set; }
        public string CreateIp { get; set; }
        public string UpdateIp { get; set; }
        public string Remark { get; set; }
    }
}
