//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehousing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Warehousing()
        {
            this.Bad = new HashSet<Bad>();
            this.Delivery = new HashSet<Delivery>();
            this.MoveBank = new HashSet<MoveBank>();
            this.ReturnPrduct = new HashSet<ReturnPrduct>();
            this.WareProduct = new HashSet<WareProduct>();
        }
    
        public int Wid { get; set; }
        public Nullable<int> WState { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public Nullable<int> Slid { get; set; }
        public Nullable<int> Tid { get; set; }
        public Nullable<int> Rid { get; set; }
        public Nullable<int> Pid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bad> Bad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Delivery> Delivery { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MoveBank> MoveBank { get; set; }
        public virtual Relation Relation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReturnPrduct> ReturnPrduct { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual User User { get; set; }
        public virtual WareState WareState { get; set; }
        public virtual WareStateType WareStateType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WareProduct> WareProduct { get; set; }
        public virtual Product Product { get; set; }
    }
}
