//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WareProduct
    {
        public int WPid { get; set; }
        public string WPname { get; set; }
        public string WPsize { get; set; }
        public Nullable<decimal> WPprice { get; set; }
        public Nullable<int> WPnum { get; set; }
        public Nullable<int> WhId { get; set; }
        public Nullable<int> Wid { get; set; }
    
        public virtual WareHouse WareHouse { get; set; }
        public virtual Warehousing Warehousing { get; set; }
    }
}
