//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WareHouse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WareHouse()
        {
            this.MoveBank = new HashSet<MoveBank>();
            this.Product = new HashSet<Product>();
            this.WareProduct = new HashSet<WareProduct>();
        }
    
        public int WhId { get; set; }
        public Nullable<int> WhTypeId { get; set; }
        public string WhName { get; set; }
        public Nullable<bool> IsForbidden { get; set; }
        public Nullable<System.DateTime> WhTime { get; set; }
        public Nullable<int> WhStateId { get; set; }
        public Nullable<int> Stid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MoveBank> MoveBank { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Product { get; set; }
        public virtual Storehouse Storehouse { get; set; }
        public virtual WareHouseType WareHouseType { get; set; }
        public virtual WhState WhState { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WareProduct> WareProduct { get; set; }
    }
}
